"""initial migration

Revision ID: 813cb9eaad28
Revises: 
Create Date: 2019-04-08 17:12:35.676894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813cb9eaad28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('username', sa.String(length=24), nullable=False, comment='用户名'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'),
    sa.Column('password', sa.String(length=128), nullable=False, comment='密码'),
    sa.Column('salt', sa.String(length=30), nullable=False, comment='密码盐'),
    sa.Column('avatar', sa.String(length=100), nullable=False, comment='头像'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('created_at', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.Integer(), nullable=True, comment='更新时间'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态,0:删除,1:正常,2:隐藏'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
